### ISSUE TITLE
Unable to apply themes: cannot find symbol for Custom React symbols

### ISSUE THREAD

**Issue by bruv-alex** [morpheusthewhite/spicetify-themes#508] opened 2021-08-21 04:42 UTC
The bug is when i choose my theme and color things, and i do try both **spicetify update** and **spicetify apply** and it says 

success Custom CSS is updated
success Custom assets are updated

and i load up spotify it still doesn't work.

Also when i do spicetify apply it says:

Applying additional modifications:
error Cannot find symbol for Custom app React symbols
panic: runtime error: index out of range [0] with length 0

and i dont know if it has anything to do with it not working but pls help me

(also im on mac if that helps)

<img width="568" alt="Screen Shot 2021-08-20 at 9 42 08 PM" src="https://user-images.githubusercontent.com/89289260/130310687-416be5ce-e250-4ef0-aab1-5271edeeccc5.png">

Heres a screenshot of my config-xpui.ini

<img width="668" alt="Screen Shot 2021-08-20 at 9 44 28 PM" src="https://user-images.githubusercontent.com/89289260/130310733-606da5fb-9a7b-4331-8288-e579a7011ae3.png">

**Comment by morpheusthewhite** [comment] 2021-08-21 07:48
This error was caused by old version of Spicetify, check if you have the latest one installed

**Comment by morpheusthewhite** [comment] 2021-08-24 10:23
Duplicate of https://github.com/morpheusthewhite/spicetify-themes/issues/453

**Closed by morpheusthewhite** 2021-08-24 10:23 UTC
