### ISSUE TITLE
Dribbblish seens broken

### ISSUE THREAD

**Issue by Skaramal7** [morpheusthewhite/spicetify-themes#525] opened 2021-08-31 23:32 UTC
**Dribblish Broken Features**
The song's image preview doesn't work as should, and the time bar it's invisible. The controls (Pause, Shuffle, Next song etc) are inverted with the Song's name and author.

**To Reproduce**
I installed everything correctly, in Windows 10, everything updated.
Then installed spicetify via Powershell, and also choose the Theme + Colour scheme via powershell.

**Screenshots**

![image_2021-08-31_140153](https://user-images.githubusercontent.com/25325687/131545381-5d92e18d-6251-4352-8bf2-6cb41f98c0ef.png)
**Logs**
The FetchEvent for "https://xpui.app.spotify.com/glue-resources/fonts/GoogleSansDisplayMedium.woff2" resulted in a network error response: the promise was rejected.
The FetchEvent for "https://xpui.app.spotify.com/glue-resources/fonts/GoogleSansDisplayRegular.woff2" resulted in a network error response: the promise was rejected.
service-worker.js:1 Uncaught (in promise) no-response: no-response :: [{"url":"https://xpui.app.spotify.com/glue-resources/fonts/GoogleSansDisplayMedium.woff2","error":{}}]
    at D._handle (https://xpui.app.spotify.com/service-worker.js:1:20428)
    at async D._getResponse (https://xpui.app.spotify.com/service-worker.js:1:10198)
service-worker.js:1 Uncaught (in promise) no-response: no-response :: [{"url":"https://xpui.app.spotify.com/glue-resources/fonts/GoogleSansDisplayRegular.woff2","error":{}}]
    at D._handle (https://xpui.app.spotify.com/service-worker.js:1:20428)
    at async D._getResponse (https://xpui.app.spotify.com/service-worker.js:1:10198)
vendor~xpui.js:29 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at c (https://xpui.app.spotify.com/vendor~xpui.js:29:2656773)
    at t.o.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2659055)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2091056
    at ka (https://xpui.app.spotify.com/vendor~xpui.js:29:2946534)
    at Ps (https://xpui.app.spotify.com/vendor~xpui.js:29:2970386)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:3190652)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2916042)
    at Is (https://xpui.app.spotify.com/vendor~xpui.js:29:2970165)
    at ws (https://xpui.app.spotify.com/vendor~xpui.js:29:2954936)
    at vs (https://xpui.app.spotify.com/vendor~xpui.js:29:2953858)
c @ vendor~xpui.js:29
GoogleSansDisplayMedium.woff2:1 Failed to load resource: net::ERR_FAILED
GoogleSansDisplayRegular.woff2:1 Failed to load resource: net::ERR_FAILED
The FetchEvent for "https://xpui.app.spotify.com/glue-resources/fonts/RobotoMedium.woff2" resulted in a network error response: the promise was rejected.
service-worker.js:1 Uncaught (in promise) no-response: no-response :: [{"url":"https://xpui.app.spotify.com/glue-resources/fonts/RobotoMedium.woff2","error":{}}]
    at D._handle (https://xpui.app.spotify.com/service-worker.js:1:20428)
    at async D._getResponse (https://xpui.app.spotify.com/service-worker.js:1:10198)
The FetchEvent for "https://xpui.app.spotify.com/glue-resources/fonts/Roboto.woff2" resulted in a network error response: the promise was rejected.
service-worker.js:1 Uncaught (in promise) no-response: no-response :: [{"url":"https://xpui.app.spotify.com/glue-resources/fonts/Roboto.woff2","error":{}}]
    at D._handle (https://xpui.app.spotify.com/service-worker.js:1:20428)
    at async D._getResponse (https://xpui.app.spotify.com/service-worker.js:1:10198)
RobotoMedium.woff2:1 Failed to load resource: net::ERR_FAILED
Roboto.woff2:1 Failed to load resource: net::ERR_FAILED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/service-worker.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/998.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED

**Specifics:**
 - OS: Windows 10 Home
 - 1.1.67.584.gc0d1ad42
 - v2.5.0
 - Dribblish Purple

**Comment by RenardFute** [comment] 2021-09-01 20:26
Duplicate of #453

**Comment by morpheusthewhite** [comment] 2021-09-04 07:29
We are tracking issues relative to Dribbblish after last update here

https://github.com/morpheusthewhite/spicetify-themes/issues/507

**Closed by morpheusthewhite** 2021-09-04 07:29 UTC
