### ISSUE TITLE
SpotifyNoControl.exe doesn't open Spotify

### ISSUE THREAD

**Issue by Tumypmyp** [morpheusthewhite/spicetify-themes#350] opened 2021-05-12 16:01 UTC
SpotifyNoControl.exe from Dribbblish theme doesn't open Spotify on Windows. But if Spotify is already opened it hides 3 dots and makes close button transparent.

**Screenshots**

**Logs**
Add logs from console. To do that
1. Run `spicetify enable-devtools` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Copy console window content.

```console
zlink.bundle.js:480 [Deprecation] SharedArrayBuffer will require cross-origin isolation as of M91, around May 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.
54895 @ zlink.bundle.js:480
127.0.0.1/api/0/envelope/?sentry_key=null&sentry_version=7:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
127.0.0.1/api/0/envelope/?sentry_key=null&sentry_version=7:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
DevTools failed to load SourceMap: Could not load content for https://zlink.app.spotify.com/zlink.bundle.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://playlist.app.spotify.com/playlist.bundle.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://zlink.app.spotify.com/css/zlink.css.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://playlist.app.spotify.com/css/playlist.css.map: Connection error: net::ERR_NAME_NOT_RESOLVED
```

**Specifics**
 - OS: Windows 10
 - Spotify version: 1.1.58.820.g2ae50076
 - Spicetify version v1.2.1
 - Theme name: Dribbblish

**Comment by morpheusthewhite** [comment] 2021-05-13 06:45
Duplicate of https://github.com/morpheusthewhite/spicetify-themes/issues/250

**Closed by morpheusthewhite** 2021-05-13 06:45 UTC
