### ISSUE TITLE
Spicetify is not showing

### ISSUE THREAD

**Issue by Idenix** [morpheusthewhite/spicetify-themes#461] opened 2021-07-12 12:21 UTC
I installed Spicetify following a tutorial on youtube, followed each step but Spotify ends up looking like the screenshot below (i installed Dribbblish base, this the reason of the green screen)
![image](https://user-images.githubusercontent.com/22416425/125286749-6fd8ca00-e31c-11eb-93e5-95741039102c.png)

**Comment by SpiritLetsPlays** [comment] 2021-07-12 14:49
Should be because of the new Spotify Update that dropped today, will hopefully be fixed soon.

**Comment by bruellkeafer** [comment] 2021-07-12 16:27
this style of Layout reminds me of the Spotify Windows-Store Version wich is not supported. Are u shure u r using the right verison (u need the Version from the official Spotify Website)

**Comment by jiznon** [comment] 2021-07-12 17:29
Same issue here. Downgrading to 1.1.62.583 and is working for the meantime.

**Comment by antonioalvasan** [comment] 2021-07-12 17:56
Same issue. I have already checked that i have the Spotify Website version, and I think i did everything fine. I have read that it may cause this issue to Spotify Premium users, which is my case.

**Comment by JumpingPig332** [comment] 2021-07-12 18:07
> Same issue here. Downgrading to 1.1.62.583 and is working for the meantime.

How?

**Comment by jiznon** [comment] 2021-07-12 18:08
> > Same issue here. Downgrading to 1.1.62.583 and is working for the meantime.
> 
> How?

Not sure what you mean. I installed 1.1.62.583 and then ran spicetify apply.

**Comment by JumpingPig332** [comment] 2021-07-12 18:09
> > > Same issue here. Downgrading to 1.1.62.583 and is working for the meantime.
> > 
> > 
> > How?
> 
> Not sure what you mean. I installed 1.1.62.583 and then ran spicetify apply.

I mean how do you install older versions, sorry

**Comment by jiznon** [comment] 2021-07-12 18:10
> > > > Same issue here. Downgrading to 1.1.62.583 and is working for the meantime.
> > > 
> > > 
> > > How?
> > 
> > 
> > Not sure what you mean. I installed 1.1.62.583 and then ran spicetify apply.
> 
> I mean how do you install older versions, sorry

Download it and install it.

**Comment by JumpingPig332** [comment] 2021-07-12 18:11
> > > > > Same issue here. Downgrading to 1.1.62.583 and is working for the meantime.
> > > > 
> > > > 
> > > > How?
> > > 
> > > 
> > > Not sure what you mean. I installed 1.1.62.583 and then ran spicetify apply.
> > 
> > 
> > I mean how do you install older versions, sorry
> 
> Download it and install it.
From where

**Comment by JumpingPig332** [comment] 2021-07-12 21:00
> > > > > > Same issue here. Downgrading to 1.1.62.583 and is working for the meantime.
> > > > > 
> > > > > 
> > > > > How?
> > > > 
> > > > 
> > > > Not sure what you mean. I installed 1.1.62.583 and then ran spicetify apply.
> > > 
> > > 
> > > I mean how do you install older versions, sorry
> > 
> > 
> > Download it and install it.
>>
> > From where

@jiznon bump

**Comment by damzbl** [comment] 2021-07-13 00:21
> > > > > > > Same issue here. Downgrading to 1.1.62.583 and is working for the meantime.
> > > > > > 
> > > > > > 
> > > > > > How?
> > > > > 
> > > > > 
> > > > > Not sure what you mean. I installed 1.1.62.583 and then ran spicetify apply.
> > > > 
> > > > 
> > > > I mean how do you install older versions, sorry
> > > 
> > > 
> > > Download it and install it.
> > > From where
> 
> @jiznon bump

Search "spotify 1.1.62" and download from uptodown. Its that easy.

**Comment by morpheusthewhite** [comment] 2021-07-13 07:06
Duplicate of https://github.com/morpheusthewhite/spicetify-themes/issues/453. Please check the issues before opening the same one.

**Closed by morpheusthewhite** 2021-07-13 07:06 UTC
