### ISSUE TITLE
Theme Fluent ERROR blank

### ISSUE THREAD

**Issue by soapsmellsnice** [morpheusthewhite/spicetify-themes#594] opened 2021-10-31 15:36 UTC
Theme Fluent ERROR blank
![adwawdaa](https://user-images.githubusercontent.com/93475261/139591106-bc649244-427f-4bdf-9e57-9d0016697992.png)

**Comment by MEXdave1997** [comment] 2021-11-01 02:30
I am getting this exact issue, and I'm not sure what exactly it could be. Other themes in the repo don't have any issues with missing icons.

**Comment by Makogai** [comment] 2021-11-01 13:01
Follow their tutorial on installing it. 
Paste this in your console (If you extracted all themes):
```
cd "$(spicetify -c | Split-Path)\Themes\Fluent"
Copy-Item fluent.js ..\..\Extensions
spicetify config extensions fluent.js
spicetify config current_theme Fluent color_scheme dark
spicetify config inject_css 1 replace_colors 1 overwrite_assets 1
spicetify apply

```

**Comment by MEXdave1997** [comment] 2021-11-01 16:00
So i double checked the install instructions, and this is the result:

![image](https://user-images.githubusercontent.com/17634751/139701746-2ec856e7-003f-4e5d-8c55-127febd32271.png)

Any ideas on why the icons at the very top are aligned left? For reference, I also applied the patch that was listed in the install tutorial:
```ini
[Patch]
xpui.js_find_8008 = ,(\w+=)32,
xpui.js_repl_8008 = ,${1}56,
```

**Comment by Makogai** [comment] 2021-11-01 16:06
> So i double checked the install instructions, and this is the result:
> 
> ![image](https://user-images.githubusercontent.com/17634751/139701746-2ec856e7-003f-4e5d-8c55-127febd32271.png)
> 
> Any ideas on why the icons at the very top are aligned left? For reference, I also applied the patch that was listed in the install tutorial:
> ```ini
> [Patch]
> xpui.js_find_8008 = ,(\w+=)32,
> xpui.js_repl_8008 = ,${1}56,
> ```

Ok that's it, the theme is outdated a bit so refer to #593

**Comment by MEXdave1997** [comment] 2021-11-01 20:14
> Ok that's it, the theme is outdated a bit so refer to #593

Awesome, this makes it look so much nicer. Thanks.

**Comment by williamckha** [comment] 2021-11-01 23:15
Duplicate of #593

**Closed by williamckha** 2021-11-01 23:15 UTC
