### ISSUE TITLE
Dribbblish pink screen after spotify update

### ISSUE THREAD

**Issue by gabrielmaster123** [morpheusthewhite/spicetify-themes#470] opened 2021-07-17 18:59 UTC
**Describe the bug**
After Spotify updated I have a Pink screen, but I can play muic with multimedia controls

**To Reproduce**
1. Update Spotify
2. Use Spicetify Backup apply with dribbblish installed
3. et voilà

**Expected behavior**
Spotify starting up normal

**Screenshots**
![image](https://user-images.githubusercontent.com/60442371/126046944-692ec09d-4c2b-4337-8ccd-0013df7866bf.png)

**Logs**
Add logs from console. To do that
1. Run `spicetify enable-devtools` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Copy console window content.

```console
![image](https://user-images.githubusercontent.com/60442371/126047035-02657b55-19f4-4be7-8426-87d8da7b820d.png)
```

**Specifics (please complete the following information):**
 - OS: Windows
 - Spotify version cant see about spotify page, prob. newest version
 - Spicetify version 1.1.63.568.gda8cb5ac with 2.3.0
 - dribbblish

**Comment by morpheusthewhite** [comment] 2021-07-18 06:02
Duplicate of https://github.com/morpheusthewhite/spicetify-themes/issues/453

**Closed by morpheusthewhite** 2021-07-18 06:02 UTC
