### ISSUE TITLE
[DribbblishDynamic] SpotifyNoControl does not work

### ISSUE THREAD

**Issue by bernawastaken** [morpheusthewhite/spicetify-themes#254] opened 2021-02-05 23:49 UTC
**Describe the bug**
When opening spotify with SpotifyNoControl.exe the window control buttons still appear and the cmd window opened by it remains on the screen.

**To Reproduce**
1. Execute SpotifyNoControl.exe provided in the Dribbblish/DribbblishDynamic folder

**Expected behavior**
Spotify would open up without the Windows window controls or the three dots on the side

**Screenshots**
![1](https://user-images.githubusercontent.com/43864475/107100360-06540d00-680c-11eb-8065-27ae0d6dfc22.png)
The window controls remain on the screen
![2](https://user-images.githubusercontent.com/43864475/107100401-25eb3580-680c-11eb-8074-b69a4ca07eb0.png)
![3](https://user-images.githubusercontent.com/43864475/107100466-5b901e80-680c-11eb-977f-bc4272cde9ac.png)
Even attempting to use `spicetify auto` as a parameter like i saw mentioned in #250 has basically the same result

**Logs**
```console
zlink.bundle.js:39 EmeEncryptionSchemePolyfill: Waiting to detect encryptionScheme support.
zlink.bundle.js:39 McEncryptionSchemePolyfill: Waiting to detect encryptionScheme support.
node_modules/kuroshiro/dist/kuroshiro.min.js:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
node_modules/kuroshiro-analyzer-kuromoji/dist/kuroshiro-analyzer-kuromoji.min.js:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://zlink.app.spotify.com/zlink.bundle.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://buddy-list.app.spotify.com/buddy-list.bundle.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://zlink.app.spotify.com/css/zlink.css.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://buddy-list.app.spotify.com/css/buddy-list.css.map: Connection error: net::ERR_NAME_NOT_RESOLVED
ogs or attach a screenshot)
```

**Specifics (please complete the following information):**
 - OS: Windows 10
 - Spotify version: 1.1.52.687.gf5565fe5
 - Spicetify version: 1.1.0
 - Theme name: DribbblishDynamic

**Comment by morpheusthewhite** [comment] 2021-02-06 07:04
Duplicate of https://github.com/morpheusthewhite/spicetify-themes/issues/250

**Closed by morpheusthewhite** 2021-02-06 07:04 UTC
